### ISSUE TITLE
failed to get chainId, falling back on net_version...

### ISSUE THREAD

**Issue by miltonisblurrd** [PatrickAlphaC/all-on-chain-generated-nft#10]
Hello I keep getting this Error, can you explain as to what i am doing wrong? Thank you

''Nothing to compile
failed to get chainId, falling back on net_version...
An unexpected error occurred:

ProviderError: Must be authenticated!
    at HttpProvider.request (/Users/blurrd/Documents/Dev/blockChain/all-on-chain-generated-nft/all-on-chain-generated-nft/node_modules/hardhat/src/internal/core/providers/http.ts:49:19)
    at HDWalletProvider.request (/Users/blurrd/Documents/Dev/blockChain/all-on-chain-generated-nft/all-on-chain-generated-nft/node_modules/hardhat/src/internal/core/providers/accounts.ts:168:34)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at GanacheGasMultiplierProvider._isGanache (/Users/blurrd/Documents/Dev/blockChain/all-on-chain-generated-nft/all-on-chain-generated-nft/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:315:30)
    at GanacheGasMultiplierProvider.request (/Users/blurrd/Documents/Dev/blockChain/all-on-chain-generated-nft/all-on-chain-generated-nft/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:304:23)
    at DeploymentsManager.getChainId (/Users/blurrd/Documents/Dev/blockChain/all-on-chain-generated-nft/all-on-chain-generated-nft/node_modules/hardhat-deploy/src/DeploymentsManager.ts:381:23)
    at DeploymentsManager.loadDeployments (/Users/blurrd/Documents/Dev/blockChain/all-on-chain-generated-nft/all-on-chain-generated-nft/node_modules/hardhat-deploy/src/DeploymentsManager.ts:554:17)
    at DeploymentsManager.runDeploy (/Users/blurrd/Documents/Dev/blockChain/all-on-chain-generated-nft/all-on-chain-generated-nft/node_modules/hardhat-deploy/src/DeploymentsManager.ts:815:5)
    at Environment._runTaskDefinition (/Users/blurrd/Documents/Dev/blockChain/all-on-chain-generated-nft/all-on-chain-generated-nft/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/Users/blurrd/Documents/Dev/blockChain/all-on-chain-generated-nft/all-on-chain-generated-nft/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)!

**Comment by miltonisblurrd** [comment]
Hello, I for some reason am still getting this issue. Looking at the forum I followed what was discussed and am still getting this error. I just want to deploy and get passed this env set up lol Would love to know what I am doing wrong so I can finally get passed this haha

**Comment by miltonisblurrd** [comment]
Now I am left with this error:

Error: insufficient funds for intrinsic transaction cost

**Comment by PatrickAlphaC** [comment]
Anything here help? https://ethereum.stackexchange.com/questions/98395/insufficient-funds-for-intrinsic-transaction-cost

**Comment by miltonisblurrd** [comment]
It worked! Thank you so much lol We are up and running!
