### ISSUE TITLE
Transactions working on SVGNFT but fails on RandomSVG 

### ISSUE THREAD

**Issue by HVjay** [PatrickAlphaC/all-on-chain-generated-nft#23]
This is similar to [this issue](https://github.com/PatrickAlphaC/all-on-chain-generated-nft/issues/16)
I am also getting the same error however it happens when waiting for the randomSVG.create() function to complete. I have a tx.wait(1) as suggested yet still receiving the same error. Deploying SVG works successfully on rinkeby. The [rinkeby etherscan](https://rinkeby.etherscan.io/tx/0x3348cac9f7562b5fdc0b0ea0f9ad9caf9d12b83df82555e0dcb60ecfb5948876) does not reveal much either. I am able to deploy the contract locally. Currently up to here [in the youtube video](https://youtu.be/9oERTH9Bkw0?t=10295)

```An unexpected error occurred:

Error: ERROR processing C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\deploy\02_deploy_randomSVG.js:
Error: transaction failed (transactionHash="0xe40a797055ade03893ed76fcbd1f51e7cbff44b457be2c442014af0d5eda6cac", transaction={"hash":"0xe40a797055ade03893ed76fcbd1f51e7cbff44b457be2c442014af0d5eda6cac","type":2,"accessList":[],"blockHash":null,"blockNumber":null,"transactionIndex":null,"confirmations":0,"from":"0x67cF969cD864E915E45d84eD416053148B61C6AE","gasPrice":{"type":"BigNumber","hex":"0x3b9aca1d"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x3b9aca11"},"maxFeePerGas":{"type":"BigNumber","hex":"0x3b9aca1d"},"gasLimit":{"type":"BigNumber","hex":"0x98967f"},"to":"0xb7402F1527bBF603018A21ee46194D3Ebc940890","value":{"type":"BigNumber","hex":"0x00"},"nonce":47,"data":"0xefc81a8c","r":"0x7e02bdbe9ec497f542c096752b123460288ab2bc6fece599d470f77e7809b2dd","s":"0x676a56f0d924fa15e5bed21b3c8df262faac36224643e3b3af2e4d9e64f3300f","v":1,"creates":null,"chainId":4}, receipt={"to":"0xb7402F1527bBF603018A21ee46194D3Ebc940890","from":"0x67cF969cD864E915E45d84eD416053148B61C6AE","contractAddress":null,"transactionIndex":23,"gasUsed":{"type":"BigNumber","hex":"0xcb9c"},"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","blockHash":"0x71e2fa49c8281e0bf27c4d47f525718dfc0f72356cbd94a2e16436d28e88e7e2","transactionHash":"0xe40a797055ade03893ed76fcbd1f51e7cbff44b457be2c442014af0d5eda6cac","logs":[],"blockNumber":10302431,"confirmations":1,"cumulativeGasUsed":{"type":"BigNumber","hex":"0x3fe15d"},"effectiveGasPrice":{"type":"BigNumber","hex":"0x3b9aca1b"},"status":0,"type":2,"byzantium":true}, code=CALL_EXCEPTION, version=providers/5.5.3)
    at Logger.makeError (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\@ethersproject\logger\src.ts\index.ts:225:28)        
    at Logger.throwError (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\@ethersproject\logger\src.ts\index.ts:237:20)       
    at EthersProviderWrapper.<anonymous> (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\@ethersproject\providers\src.ts\base-provider.ts:1352:24)
    at step (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\@ethersproject\providers\lib\base-provider.js:48:23)
    at Object.next (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\@ethersproject\providers\lib\base-provider.js:29:53)      
    at fulfilled (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\@ethersproject\providers\lib\base-provider.js:20:58)        
    at DeploymentsManager.executeDeployScripts (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1223:19)
    at DeploymentsManager.runDeploy (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1053:5)
    at SimpleTaskDefinition.action (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\hardhat-deploy\src\index.ts:422:5)        
    at Environment._runTaskDefinition (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\hardhat\src\internal\core\runtime-environment.ts:217:14)
    at Environment.run (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\hardhat\src\internal\core\runtime-environment.ts:129:14)
    at SimpleTaskDefinition.action (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\hardhat-deploy\src\index.ts:568:32)       
    at Environment._runTaskDefinition (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\hardhat\src\internal\core\runtime-environment.ts:217:14)
    at Environment.run (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\hardhat\src\internal\core\runtime-environment.ts:129:14)
    at SimpleTaskDefinition.action (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\hardhat-deploy\src\index.ts:653:5)        
    at Environment._runTaskDefinition (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\hardhat\src\internal\core\runtime-environment.ts:217:14)

harri@DESKTOP-01G6233 MINGW64 ~/Desktop/SideProj/Prophecy/Prophecy-Smart-Contract
$ npx hardhat deploy --network rinkeby --tags rsvg
Compiled 1 Solidity file successfully
---------------------------------
deploying "RandomSVG" (tx: 0x0513be012626dc4f663e76dbce4e054b5e9e611c2ddbcc77ab6ef7478c8734a5)...: deployed at 0xaC130C6ECa213451b0eeEbAe74Dfc6BbAC840382 with 4547588 gas
You have deployed your NFT contract!
Verify with:
 npx hardhat verify --network rinkeby 0xaC130C6ECa213451b0eeEbAe74Dfc6BbAC840382 0x6168499c0cFfCaCD319c818142124B7A15E857ab 0x01BE23585060835E02B77ef475b0Cc51aA1e0709 0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc 250000000000000000
linkTokenContract
accounts
Duplicate definition of Transfer (Transfer(address,address,uint256,bytes), Transfer(address,address,uint256))
fund_tx
creation_tx
An unexpected error occurred:

Error: ERROR processing C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\deploy\02_deploy_randomSVG.js:
Error: transaction failed (transactionHash="0x020c88c9742991bb8c93d018daa153ce6916916d8fd726c9adce30240da0f2e2", transaction={"hash":"0x020c88c9742991bb8c93d018daa153ce6916916d8fd726c9adce30240da0f2e2","type":2,"accessList":[],"blockHash":null,"blockNumber":null,"transactionIndex":null,"confirmations":0,"from":"0x67cF969cD864E915E45d84eD416053148B61C6AE","gasPrice":{"type":"BigNumber","hex":"0x59682f0b"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"maxFeePerGas":{"type":"BigNumber","hex":"0x59682f0b"},"gasLimit":{"type":"BigNumber","hex":"0x98967f"},"to":"0xaC130C6ECa213451b0eeEbAe74Dfc6BbAC840382","value":{"type":"BigNumber","hex":"0x00"},"nonce":50,"data":"0xefc81a8c","r":"0x02bad9fdecc258b0d4435792528e50eff08489ae6171a989f71b6bab4c613923","s":"0x6ed9b5942dff55b78b7fcb0c0fae10d475518b9b839af858fa9fcd9badef298b","v":1,"creates":null,"chainId":4}, receipt={"to":"0xaC130C6ECa213451b0eeEbAe74Dfc6BbAC840382","from":"0x67cF969cD864E915E45d84eD416053148B61C6AE","contractAddress":null,"transactionIndex":40,"gasUsed":{"type":"BigNumber","hex":"0xd8e6"},"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","blockHash":"0x5ea44c88f90f0bf79f91570c57648b694ec9af1f0183055b4dc5c7bc6a277cb7","transactionHash":"0x020c88c9742991bb8c93d018daa153ce6916916d8fd726c9adce30240da0f2e2","logs":[],"blockNumber":10302445,"confirmations":1,"cumulativeGasUsed":{"type":"BigNumber","hex":"0x218ee3"},"effectiveGasPrice":{"type":"BigNumber","hex":"0x59682f09"},"status":0,"type":2,"byzantium":true}, code=CALL_EXCEPTION, version=providers/5.5.3)
    at Logger.makeError (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\@ethersproject\logger\src.ts\index.ts:225:28)        
    at Logger.throwError (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\@ethersproject\logger\src.ts\index.ts:237:20)       
    at EthersProviderWrapper.<anonymous> (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\@ethersproject\providers\src.ts\base-provider.ts:1352:24)
    at step (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\@ethersproject\providers\lib\base-provider.js:48:23)
    at Object.next (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\@ethersproject\providers\lib\base-provider.js:29:53)      
    at fulfilled (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\@ethersproject\providers\lib\base-provider.js:20:58)        
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:497:9)
    at DeploymentsManager.executeDeployScripts (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1223:19)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:497:9)
    at DeploymentsManager.runDeploy (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1053:5)
    at SimpleTaskDefinition.action (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\hardhat-deploy\src\index.ts:422:5)        
    at Environment._runTaskDefinition (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\hardhat\src\internal\core\runtime-environment.ts:217:14)
    at Environment.run (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\hardhat\src\internal\core\runtime-environment.ts:129:14)
    at SimpleTaskDefinition.action (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\hardhat-deploy\src\index.ts:568:32)       
    at Environment._runTaskDefinition (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\hardhat\src\internal\core\runtime-environment.ts:217:14)
    at Environment.run (C:\Users\harri\Desktop\SideProj\Prophecy\Prophecy-Smart-Contract\node_modules\hardhat\src\internal\core\runtime-environment.ts:129:14)
```

**Comment by HVjay** [comment]
Here is my code for 02_deploy_randomSVG.js

```
let {
  networkConfig,
  getNetworkIdFromName,
} = require("../helper-hardhat-config");

module.exports = async ({ getNamedAccounts, deployments, getChainId }) => {
  const { deploy, get, log } = deployments;
  const { deployer } = await getNamedAccounts();
  const chainId = await getChainId();

  let linkTokenAddress, vrfCoordinatorAddress;

  if (chainId == 31337) {
    let linkToken = await get("LinkToken");
    let vrfCoordinatorMock = await get("VRFCoordinatorMock");
    linkTokenAddress = linkToken.address;
    vrfCoordinatorAddress = vrfCoordinatorMock.address;
  } else {
    linkTokenAddress = networkConfig[chainId]["linkToken"];
    vrfCoordinatorAddress = networkConfig[chainId]["vrfCoordinator"];
  }

  const keyHash = networkConfig[chainId]["keyHash"];
  const fee = networkConfig[chainId]["fee"];
  let args = [vrfCoordinatorAddress, linkTokenAddress, keyHash, fee];
  log("---------------------------------");
  const RandomSVG = await deploy("RandomSVG", {
    from: deployer,
    args: args,
    log: true,
  });
  log("You have deployed your NFT contract!");
  const networkName = networkConfig[chainId]["name"];
  log(
    `Verify with: \n npx hardhat verify --network ${networkName} ${
      RandomSVG.address
    } ${args.toString().replace(/,/g, " ")}`
  );

  const linkTokenContract = await ethers.getContractFactory("LinkToken");
  log("linkTokenContract");
  const accounts = await hre.ethers.getSigners();
  log("accounts");
  const signer = accounts[0];
  const linkToken = new ethers.Contract(
    linkTokenAddress,
    linkTokenContract.interface,
    signer
  );
  let fund_tx = await linkToken.transfer(RandomSVG.address, fee);
  log("fund_tx");
  await fund_tx.wait(1);

  const RandomSVGContract = await ethers.getContractFactory("RandomSVG");
  const randomSVG = new ethers.Contract(
    RandomSVG.address,
    RandomSVGContract.interface,
    signer
  );
  let creation_tx = await randomSVG.create({ gasLimit: 9999999 });
  log("creation_tx");
  let receipt = await creation_tx.wait(1);
  log("receipt");
  let tokenId = receipt.events[3].topics[2];
  log("tokenId");
  log(`You've made your NFT! This is token number ${tokenId}`);
  log("Lets wait for chainlink node to respond");
  if (chainId != 31337) {
    await new Promise((r) => setTimeout(r, 18000));
    log(`Now let's finish the mint...`);
    let finish_tx = await randomSVG.finishMint(tokenId, { gasLimit: 2000000 });
    await finish_tx.wait(1);
    log(`You can view the tokenURI here ${await randomSVG.tokenURI(tokenId)}`);
  } else {
    const VRFCoordinatorMock = await deployments.get("VRFCoordinatorMock");
    vrfCoordinator = await ethers.getContractAt(
      "VRFCoordinatorMock",
      VRFCoordinatorMock.address,
      signer
    );
    let vrf_tx = await vrfCoordinator.callBackWithRandomness(
      receipt.logs[3].topics[1],
      77777,
      randomSVG.address
    );
    await vrf_tx.wait(1);
    log("Now let's finish the mint!");
    let finish_tx = await randomSVG.finishMint(tokenId, { gasLimit: 2000000 });
    await finish_tx.wait(1);
    log(`You can view the tokenURI here: ${await randomSVG.tokenURI(tokenId)}`);
  }
};

module.exports.tags = ["all", "rsvg"];
```

**Comment by PatrickAlphaC** [comment]
If you look at the [transaction](https://rinkeby.etherscan.io/tx/0x6b773fad91e9cdc08ad0a49e639f6496f793b780619e969bf10e2ed155a98251), it says `tokenURI is already set!` so we know that's the issue.

And if you look at [etherescan](https://rinkeby.etherscan.io/address/0x3dcf7a872d6d280926b82300b6bf243e00b9bbfd) we can see that you are actually calling `finishmint` twice. 

And yep! It looks like you're calling it twice:

```javascript
  if (chainId != 31337) {
    await new Promise((r) => setTimeout(r, 18000));
    log(`Now let's finish the mint...`);
    let finish_tx = await randomSVG.finishMint(tokenId, { gasLimit: 2000000 });
//////////////////////////////////
    await finish_tx.wait(1);
//////////////////////////////////
    log(`You can view the tokenURI here ${await randomSVG.tokenURI(tokenId)}`);
  } else {
    const VRFCoordinatorMock = await deployments.get("VRFCoordinatorMock");
    vrfCoordinator = await ethers.getContractAt(
      "VRFCoordinatorMock",
      VRFCoordinatorMock.address,
      signer
    );
    let vrf_tx = await vrfCoordinator.callBackWithRandomness(
      receipt.logs[3].topics[1],
      77777,
      randomSVG.address
    );
    await vrf_tx.wait(1);
    log("Now let's finish the mint!");
    let finish_tx = await randomSVG.finishMint(tokenId, { gasLimit: 2000000 });
//////////////////////////////////
    await finish_tx.wait(1); //HERE!!!!
//////////////////////////////////
    log(`You can view the tokenURI here: ${await randomSVG.tokenURI(tokenId)}`);
  }
```

**Comment by PatrickAlphaC** [comment]
I'll fix!

**Comment by PatrickAlphaC** [comment]
Ok this should be fixed in https://github.com/PatrickAlphaC/all-on-chain-generated-nft/commit/63809855e64ed05d51fd835092595feb3cbfbba6

Could you pull and try again? Thanks for the issue!

**Comment by PatrickAlphaC** [comment]
Closing for now. Thanks for this issue!
