### ISSUE TITLE
what am i missing ... have a .env file ... deleted username ... but yea need help ... 

### ISSUE THREAD

**Issue by nuprince** [PatrickAlphaC/all-on-chain-generated-nft#28]
An unexpected error occurred:

Error: Cannot find module 'dotenv'
Require stack:
- /Users//demo/all-on-chain-nft/hardhat.config.js
- /Users//demo/all-on-chain-nft/node_modules/hardhat/internal/core/config/config-loading.js
- /Users//demo/all-on-chain-nft/node_modules/hardhat/internal/cli/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users//demo/all-on-chain-nft/hardhat.config.js:10:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users//demo/all-on-chain-nft/hardhat.config.js',
    '/Users//demo/all-on-chain-nft/node_modules/hardhat/internal/core/config/config-loading.js',
    '/Users//demo/all-on-chain-nft/node_modules/hardhat/internal/cli/cli.js'
  ]
}

**Comment by PatrickAlphaC** [comment]
1. What command are you running? 
2. Where are you running it?
3. Try running `yarn add dotenv` and then running whatever command you're running.

**Comment by nuprince** [comment]
thanks ... i found the solution .. didn't have all the dependencies ...
