### ISSUE TITLE
Amount of tokens required to mint rsvg using polygon?

### ISSUE THREAD

**Issue by yaizudamashii** [PatrickAlphaC/all-on-chain-generated-nft#3]
Hi Patrick, in the video, to run the command

`npx hardhat deploy --network polygon --tags rsvg`

you mentioned that it would cost you about $3 (I know that the price changes, so it is just a ballpark) but I have 0.05 ETH, 1.4 LINK, and 11 MATIC, but I am still getting insufficient funds.  Is there any other token I need to be able to deploy on polygon?

I've modified `02_Deploy_RandomSVG.js: 62` to the one you had in the video,
`tx = await randomSVG.finishMint(tokenId, { gasLimit: 2000000, gasPrice: 20000000000 })`

**Comment by PatrickAlphaC** [comment]
When you deploy to a testnet, how much gas are you using?

**Comment by yaizudamashii** [comment]
When I deployed rsvg to rinkeby I used 4933802 gas and 1 LINK.

**Comment by PatrickAlphaC** [comment]
So it'll take that much gas. Please make the gaslimit more than `4933802`.

**Comment by yaizudamashii** [comment]
I increased the gasLimit to 8000000 then to 16000000 but still failed...

**Comment by yaizudamashii** [comment]
Hi Patrick,

The code was edited as follows:
In `02_Deploy_RandomSVG.js`

line 52:
`tx = await randomSVG.create({ gasLimit: 300000 })`
was changed to 
`tx = await randomSVG.create({ gasLimit: 16000000 })`

line 60:
`tx = await randomSVG.finishMint(tokenId, { gasLimit: 2000000 })`
was changed to 
`tx = await randomSVG.finishMint(tokenId, { gasLimit: 16000000, gasPrice: 20000000000 })`

line 69:
`tx = await randomSVG.finishMint(tokenId, { gasLimit: 2000000 })`
was changed to 
`tx = await randomSVG.finishMint(tokenId, { gasLimit: 16000000 })`

in `hardhat.config.js` all accounts were changed to use [PRIVATE_KEY] rather than MNEMONIC.


The command being run is
`npx hardhat deploy --network polygon --tags rsvg`

The error log is as follows:
```
✗ npx hardhat deploy --network polygon --tags rsvg
You are using a version of Node.js that is not supported by Hardhat, and it may work incorrectly, or not work at all.

Please, upgrade your Node.js version.

To learn more about which versions of Node.js are supported go to https://hardhat.org/nodejs-versions
Nothing to compile
----------------------------------------------------
deploying "RandomSVG"An unexpected error occurred:

Error: ERROR processing /Users/yuki/Developer/all-on-chain-generated-nft/deploy/02_Deploy_RandomSVG.js:
Error: insufficient funds for intrinsic transaction cost (error={"name":"ProviderError","code":-32000,"_isProviderError":true}, method="sendTransaction", transaction=undefined, code=INSUFFICIENT_FUNDS, version=providers/5.4.5)
    at Logger.makeError (/Users/yuki/Developer/all-on-chain-generated-nft/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
    at Logger.throwError (/Users/yuki/Developer/all-on-chain-generated-nft/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
    at checkError (/Users/yuki/Developer/all-on-chain-generated-nft/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:53:16)
    at /Users/yuki/Developer/all-on-chain-generated-nft/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:215:24
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at DeploymentsManager.executeDeployScripts (/Users/yuki/Developer/all-on-chain-generated-nft/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1014:19)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at DeploymentsManager.runDeploy (/Users/yuki/Developer/all-on-chain-generated-nft/node_modules/hardhat-deploy/src/DeploymentsManager.ts:849:5)
    at Environment._runTaskDefinition (/Users/yuki/Developer/all-on-chain-generated-nft/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/Users/yuki/Developer/all-on-chain-generated-nft/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at SimpleTaskDefinition.action (/Users/yuki/Developer/all-on-chain-generated-nft/node_modules/hardhat-deploy/src/index.ts:446:32)
    at Environment._runTaskDefinition (/Users/yuki/Developer/all-on-chain-generated-nft/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/Users/yuki/Developer/all-on-chain-generated-nft/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at SimpleTaskDefinition.action (/Users/yuki/Developer/all-on-chain-generated-nft/node_modules/hardhat-deploy/src/index.ts:521:5)
    at Environment._runTaskDefinition (/Users/yuki/Developer/all-on-chain-generated-nft/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    ```
    
    The amounts of assets in the metamask wallet for mainnet are 0.0551 ETH, 1.453 LINK, and 11.305 MATIC

**Comment by yaizudamashii** [comment]
In terms of the Node version warning, it probably is ok as testnet deployments worked...

**Comment by PatrickAlphaC** [comment]
`Please, upgrade your Node.js version.`

Can you upgrade your node version and reinstall please? Closing for now.
